name: Lottery
main: net.erbros.lottery.Lottery
version: maven-version-number
authors: [Erbros, KHobbits, Omnivion, Lactem, graywolf336]
depend: [Vault]
api-version: 1.13

commands:
  lottery:
    description: Provides access to Permissions commands and information.
    permission: lottery.buy
    usage: /<command> [winners|claim|help|messages|buy [amount]]
    aliases: [lot,lotto]

permissions:
  lottery.*:
      description: Full access to Lottery plugin.
      children:
          lottery.buy: true
          lottery.admin.draw: true
          lottery.admin.addtopot: true
  lottery.buy:
      description: Basic lottery rights. Can buy, check lottery info and claim winnings.
      default: true
  lottery.admin.draw:
      description: Access to /lottery draw command.
      default: op
  lottery.admin.addtopot:
      description: Access to /lottery addtopot command.
      default: op
